### ISSUE TITLE
请问Centos7 上直接执行one-key-kms-centos.sh脚本旧可以了？

### ISSUE THREAD

**Issue by aglent** [dakkidaze/one-key-kms#1]
第一次用，不是很清楚，请问只要执行one-key-kms-centos.sh脚本就能设置好KMS服务器了吗？然后客户端输入相应命令就可以激活了？

**Comment by dakkidaze** [comment]
先用这个装上，然后再用kms.sh脚本开启

**Comment by aglent** [comment]
非常感谢！ 脚本真实用！
